### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fenhl** [fenhl/oottracker#23]
Would be nice to include a version of the GUI compiled for Linux in the releases. Needs the following addition to `.cargo/config.toml`:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
```

Once the GUI runs, auto-tracking on Project64 (via Wine) and RetroArch should work for free. BizHawk runs on Linux but the N64 plugin doesn't work.

Open questions:

* How to distribute the Linux binary? Just upload it? Maybe host a package source for apt?
* How should updates work? (Integration with package managers would probably be best, but then all the different package managers have to be supported.)
